import { Router } from 'express';
import { signup, login, userinfo, forgetPassword, logout } from '../controllers/userController';
import verifyToken from '../middleware/verifyToken';
const router = Router();
router.post('/signup', signup);
router.post('/login', login);
router.post('/forgetPassword', forgetPassword);
router.get('/userinfo', verifyToken, userinfo);
router.get('/logout', logout);
export default router;
