import { Router } from 'express';
import { signup, login, userinfo, forgetPassword, logout } from '../controllers/userController';
import verifyToken from '../middleware/verifyToken';
import limiter from '../middleware/rateLimit';
import validateRequest from '../middleware/validateRequest';
import { ValidateSignup } from '../validates/userValidate';
const router = Router();
router.post('/signup', limiter, validateRequest(ValidateSignup, 'body'), signup);
router.post('/login', limiter, login);
router.post('/forgetPassword', forgetPassword);
router.get('/userinfo', verifyToken, userinfo);
router.get('/logout', logout);
export default router;
