import { Router } from 'express';
import { getSubjectWords, getWordExample, getDailyWords, checkIsDaily, saveLearnedWord, deleteLearnedWord } from '../controllers/wordController';
import verifyToken from '../middleware/verifyToken';
const router = Router();
router.get('/checkIsDaily', verifyToken, checkIsDaily);
router.get('/subjectWords', getSubjectWords);
router.get('/wordExample', getWordExample);
router.post('/saveLearnedWord', saveLearnedWord);
router.delete('/learnedWord/:wordId', deleteLearnedWord);
export default router;
